import { Urbanist } from "next/font/google";
import "../styles/main.scss";
import { Providers } from "@/context/Providers";

const inter = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "Shopay",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
