"use client";
import FormHeader from "@/components/backoffice/formComponents/FormHeader";
import ImageInput from "@/components/backoffice/formComponents/ImageInput";
import SubmitButton from "@/components/backoffice/formComponents/SubmitButton";
import TextareaInput from "@/components/backoffice/formComponents/TextAreaInput";
import TextInput from "@/components/backoffice/formComponents/TextInput";
import { generateSlug } from "@/lib/generateSlug";
import { useState } from "react";
import { useForm } from "react-hook-form";
import "@uploadthing/react/styles.css";
import { makePostRequest } from "@/lib/apiRequest";
import SelectInput from "@/components/backoffice/formComponents/SelectInput";
import ToggleInput from "@/components/backoffice/formComponents/ToggleInput";

const NewCatagory = () => {
  const markets = [
    {
      id: 1,
      title: "Fresh Fruits Market",
    },
    {
      id: 2,
      title: "Sproutes Farmers Market",
    },
    {
      id: 3,
      title: "Gemuse Market",
    },
    {
      id: 4,
      title: "Hardware's Market",
    },
  ];
  const [imageUrl, setImageUrl] = useState("");
  const [loading, setLoading] = useState(false);
  const {
    register,
    reset,
    watch,
    handleSubmit,
    formState: { errors },
  } = useForm({
    defaultValues: {
      isActive: true,
    },
  });
  const isActive = watch("isActive");

  const onSubmitForm = async (data) => {
    //generate the title slug
    const slug = generateSlug(data.title);
    data.slug = slug;
    data.imageUrl = imageUrl;
    makePostRequest(setLoading, "api/categories", data, "Category", reset);
    setImageUrl("");
  };
  return (
    <div>
      <FormHeader headerTitle="New Category" />
      {/* ID = autogenerated | TITLE | SLUG = autogenerated | DESCRIPTION | IMAGE */}
      <form
        onSubmit={handleSubmit(onSubmitForm)}
        className="w-full max-w-2xl p-4 bg-gray-200 border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700 mx-auto my-3 "
      >
        <div className="grid gap-4 sm:grid-cols-2 sm:gap-6">
          <TextInput
            label="Category Title"
            name="title"
            register={register}
            errors={errors}
            className="w-full font-poppins"
            placeHolder="Category title"
          />
          <SelectInput
            label="Select Market"
            name="marketIds"
            register={register}
            errors={errors}
            className="w-full font-poppins"
            options={markets}
            multiple={false}
          />
          <TextareaInput
            label="Category Description"
            name="description"
            register={register}
            errors={errors}
            placeHolder="Category description"
          />
          {/* CHECKBOX TOGGLE */}
          <ToggleInput
            label="Publish Your Category"
            nameWatched="isActive"
            isTrue={isActive}
            trueTitle="Active"
            falseTitle="Inactive"
            register={register}
          />
          <ImageInput
            label="Category Image"
            endpoint="categoryImageUploader"
            imageUrl={imageUrl}
            setImageUrl={setImageUrl}
          />

          <SubmitButton
            buttonTitle="Create Category"
            loadingButtonTitle="Creating new category please wait..."
            isLoading={loading}
          />
        </div>
      </form>
    </div>
  );
};

export default NewCatagory;
