"use client";
import FormHeader from "@/components/backoffice/formComponents/FormHeader";
import ImageInput from "@/components/backoffice/formComponents/ImageInput";
import SubmitButton from "@/components/backoffice/formComponents/SubmitButton";
import TextareaInput from "@/components/backoffice/formComponents/TextAreaInput";
import TextInput from "@/components/backoffice/formComponents/TextInput";
import { useState } from "react";
import { useForm } from "react-hook-form";
import "@uploadthing/react/styles.css";
import { makePostRequest } from "@/lib/apiRequest";
import ToggleInput from "@/components/backoffice/formComponents/ToggleInput";
import { useRouter } from "next/navigation";

const NewBanner = () => {
  const [imageUrl, setImageUrl] = useState("");
  const [loading, setLoading] = useState(false);
  //UPLOADING IMAGE STATES
  const [uploadLoading, setUploadLoading] = useState(false);
  let isUploading = false;
  const {
    register,
    reset,
    watch,
    handleSubmit,
    formState: { errors },
  } = useForm({
    defaultValues: {
      isActive: true,
    },
  });
  const isActive = watch("isActive");
  //REDIRECTION
  const router = useRouter();
  const redirectFunction = () => {
    router.push("/dashboard/banners");
  };

  const onSubmitForm = async (data) => {
    data.imageUrl = imageUrl;
    makePostRequest(
      setLoading,
      "api/banners",
      data,
      "Banner",
      reset,
      redirectFunction
    );
    setImageUrl("");
  };

  //get isUploading value from imageinput component

  const getValue = (value) => {
    console.log("PARENT", isUploading);
    isUploading = value;
    if (isUploading) {
      setUploadLoading(true);
    } else {
      setUploadLoading(false);
    }
    console.log("PARENT", isUploading);
  };

  return (
    <div>
      <FormHeader headerTitle="New Banner" />
      {/* ID = autogenerated | TITLE | SLUG = autogenerated | DESCRIPTION | IMAGE */}
      <form
        onSubmit={handleSubmit(onSubmitForm)}
        className="w-full max-w-4xl p-4 bg-gray-200 border border-gray-200 rounded-lg shadow sm:p-6 md:p-8 dark:bg-gray-800 dark:border-gray-700 mx-auto my-3 "
      >
        <div className="flex flex-col gap-4 sm:grid-cols-2 sm:gap-6">
          <TextInput
            label="Banner Title"
            name="title"
            register={register}
            errors={errors}
            placeHolder="Banner title"
          />
          <TextInput
            label="Banner Link"
            name="link"
            type="url"
            register={register}
            errors={errors}
            placeHolder="Banner Link"
          />
          {/* CHECKBOX TOGGLE */}
          <ToggleInput
            label="Publish Your Banner"
            nameWatched="isActive"
            isTrue={isActive}
            trueTitle="Active"
            falseTitle="Inactive"
            register={register}
          />
          {/* CONFIGURE ENDPOINT IN COREJS  */}
          <ImageInput
            label="Banner Image"
            endpoint="bannerImageUploader"
            imageUrl={imageUrl}
            setImageUrl={setImageUrl}
            getValue={getValue}
          />

          <SubmitButton
            buttonTitle="Create Banner"
            loadingButtonTitle="Creating new banner please wait..."
            isLoading={loading}
            uploadLoading={uploadLoading}
            loadingUploadTitle="Uploading Banner Image please wait..."
          />
        </div>
      </form>
    </div>
  );
};

export default NewBanner;
